//! Code generation from decoder specifications

use crate::spec::{DecoderSpec, EncodingSpec};
use anyhow::Result;
use std::collections::HashMap;

pub struct GeneratedCode {
    pub files: HashMap<String, String>,
}

/// Generate all code for a decoder from its specification
pub fn generate(spec: &DecoderSpec) -> Result<GeneratedCode> {
    let mut files = HashMap::new();

    // Generate Cargo.toml
    files.insert("Cargo.toml".to_string(), generate_cargo_toml(spec));

    // Generate lib.rs
    files.insert("src/lib.rs".to_string(), generate_lib_rs(spec));

    // Generate parsing.rs
    files.insert("src/parsing.rs".to_string(), generate_parsing_rs(spec));

    // Generate types.rs
    files.insert("src/types.rs".to_string(), generate_types_rs(spec));

    // Generate tests
    files.insert(
        "tests/property_tests.rs".to_string(),
        generate_property_tests(spec),
    );

    // Generate README
    files.insert("README.md".to_string(), generate_readme(spec));

    Ok(GeneratedCode { files })
}

fn generate_cargo_toml(spec: &DecoderSpec) -> String {
    let chain_lower = spec.chain.name.to_lowercase();

    // Determine hash dependencies
    let hash_deps = match spec.encoding.hash.as_str() {
        "sha256" | "double-sha256" => r#"sha2 = { workspace = true }"#,
        "keccak256" => r#"sha3 = { workspace = true }"#,
        "blake2b" => r#"blake2 = "0.10""#,
        "blake3" => r#"blake3 = "1.5""#,
        _ => r#"sha2 = { workspace = true }  # TODO: Add correct hash"#,
    };

    format!(
        r#"[package]
name = "decoder-{chain_lower}"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "{chain_name} transaction decoder for universal-decoder (GENERATED)"

[dependencies]
universal-decoder-core = {{ path = "../universal-decoder-core" }}
decoder-primitives = {{ path = "../decoder-primitives" }}
decoder-encodings = {{ path = "../decoder-encodings" }}
serde = {{ workspace = true }}
thiserror = {{ workspace = true }}
{hash_deps}

[dev-dependencies]
serde_json = {{ workspace = true }}
proptest = {{ workspace = true }}
decoder-test-utils = {{ path = "../decoder-test-utils" }}

# NOTE: This crate was GENERATED by decoder-generator.
# To regenerate: cargo run -p decoder-generator -- generate specs/{chain_lower}.toml
"#,
        chain_lower = chain_lower,
        chain_name = spec.chain.name,
        hash_deps = hash_deps
    )
}

fn generate_lib_rs(spec: &DecoderSpec) -> String {
    let chain_name = &spec.chain.name;
    let chain_id = spec.chain.chain_id;
    let chain_family = &spec.chain.family;
    let chain_struct = format!("{}Chain", chain_name);
    let tx_struct = format!("{}Transaction", chain_name);
    let decoder_struct = format!("{}Decoder", chain_name);

    let description = spec
        .chain
        .description
        .as_ref()
        .map(|d| format!("//! {}\n//!", d))
        .unwrap_or_default();

    format!(
        r#"//! {chain_name} transaction decoder - GENERATED CODE
//!
{description}
//! This decoder was automatically generated from a specification.
//! To regenerate: cargo run -p decoder-generator -- generate specs/{chain_lower}.toml
//!
//! ## Encoding
//! - Endianness: {endianness}
//! - Hash: {hash}
//! - Variable encoding: {var_encoding}

use decoder_primitives::prelude::*;
use std::io::Cursor;

pub mod parsing;
pub mod types;

use parsing::*;
pub use types::{tx_struct};

/// {chain_name} chain identity
#[derive(Debug, Clone, Copy)]
pub struct {chain_struct};

impl ChainIdentity for {chain_struct} {{
    fn chain_id(&self) -> u64 {{
        {chain_id}
    }}

    fn chain_name(&self) -> &str {{
        "{chain_name}"
    }}

    fn chain_family(&self) -> ChainFamily {{
        ChainFamily::{family_variant}
    }}
}}

/// {chain_name} decoder
pub struct {decoder_struct};

impl ChainDecoder for {decoder_struct} {{
    type TxSpecific = {tx_struct};
    type Chain = {chain_struct};

    fn chain() -> Self::Chain {{
        {chain_struct}
    }}

    fn decode(raw_bytes: &[u8]) -> Result<Self::TxSpecific> {{
        Self::validate_format(raw_bytes)?;

        let mut cursor = Cursor::new(raw_bytes);

        // TODO: Generate field parsing based on spec
        // This is a placeholder implementation.
        // Run `cargo run -p decoder-generator -- regenerate` after
        // implementing full codegen.

        unimplemented!("Field parsing generation in progress")
    }}

    fn validate_format(raw_bytes: &[u8]) -> Result<()> {{
        if raw_bytes.is_empty() {{
            return Err(DecoderError::invalid_structure(
                "{chain_name} transaction cannot be empty"
            ));
        }}

        if raw_bytes.len() < 10 {{
            return Err(DecoderError::invalid_structure(format!(
                "{chain_name} transaction too small: {{}} bytes",
                raw_bytes.len()
            )));
        }}

        Ok(())
    }}
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn test_chain_identity() {{
        let chain = {decoder_struct}::chain();
        assert_eq!(chain.chain_id(), {chain_id});
        assert_eq!(chain.chain_name(), "{chain_name}");
    }}

    #[test]
    fn test_validate_format() {{
        assert!({decoder_struct}::validate_format(&[]).is_err());
        assert!({decoder_struct}::validate_format(&[0x01]).is_err());
    }}
}}
"#,
        chain_name = chain_name,
        chain_lower = chain_name.to_lowercase(),
        chain_id = chain_id,
        chain_struct = chain_struct,
        tx_struct = tx_struct,
        decoder_struct = decoder_struct,
        description = description,
        endianness = spec.encoding.endianness,
        hash = spec.encoding.hash,
        var_encoding = spec
            .encoding
            .var_encoding
            .as_ref()
            .unwrap_or(&"none".to_string()),
        family_variant = match chain_family.as_str() {
            "utxo" => "Utxo",
            "account" => "Account",
            "instruction" => "Instruction",
            _ => "Custom",
        }
    )
}

fn generate_parsing_rs(spec: &DecoderSpec) -> String {
    let encoding_imports = generate_encoding_imports(&spec.encoding);

    format!(
        r#"//! Pure Rust {chain_name} transaction parsing utilities
//!
//! GENERATED from specification.

use decoder_primitives::prelude::*;
use std::io::Read;
{encoding_imports}

pub const MAX_TRANSACTION_SIZE: usize = 100_000;
pub const MAX_SCRIPT_SIZE: usize = 10_000;

// TODO: Generate parsing functions based on spec fields
"#,
        chain_name = spec.chain.name,
        encoding_imports = encoding_imports
    )
}

fn generate_encoding_imports(encoding: &EncodingSpec) -> String {
    let mut imports = vec![];

    if let Some(ref var_enc) = encoding.var_encoding {
        match var_enc.as_str() {
            "varint" => imports.push("use decoder_encodings::varint::*;"),
            "rlp" => imports.push("use decoder_encodings::rlp::*;"),
            "compact-u16" => imports.push("use decoder_encodings::compact_u16::*;"),
            "uleb128" | "bcs" => imports.push("use decoder_encodings::bcs::*;"),
            _ => {}
        }
    }

    if !imports.is_empty() {
        format!("\n{}", imports.join("\n"))
    } else {
        String::new()
    }
}

fn generate_types_rs(spec: &DecoderSpec) -> String {
    let tx_struct = format!("{}Transaction", spec.chain.name);
    let chain_struct = format!("{}Chain", spec.chain.name);

    let hash_import = match spec.encoding.hash.as_str() {
        "sha256" | "double-sha256" => "use sha2::{Digest, Sha256};",
        "keccak256" => "use sha3::{Digest, Keccak256};",
        "blake2b" => "use blake2::{Blake2b512, Digest};",
        "blake3" => "// use blake3;",
        _ => "// TODO: Add hash import",
    };

    format!(
        r#"//! {chain_name}-specific transaction types
//!
//! GENERATED from specification.

use universal_decoder_core::prelude::*;
use crate::{chain_struct};
{hash_import}

/// {chain_name} transaction representation
#[derive(Debug, Clone)]
pub struct {tx_struct} {{
    pub raw_bytes: Vec<u8>,
    // TODO: Generate fields based on spec
}}

impl {tx_struct} {{
    /// Calculate transaction ID
    pub fn txid(&self) -> Vec<u8> {{
        // TODO: Generate based on hash spec
        {hash_impl}
    }}
}}

impl<'a> Canonicalizer<'a> for {tx_struct} {{
    const VERSION: u8 = 1;

    fn canonicalize(&'a self) -> Result<TxIR<'a, 1>> {{
        // TODO: Generate based on spec
        unimplemented!("Canonicalization generation in progress")
    }}

    fn validate(&self) -> Result<()> {{
        Ok(())
    }}
}}

impl TxHashable for {tx_struct} {{
    fn to_canonical_bytes(&self) -> Vec<u8> {{
        self.raw_bytes.clone()
    }}

    fn compute_hash(&self) -> Vec<u8> {{
        self.txid()
    }}
}}
"#,
        chain_name = spec.chain.name,
        chain_struct = chain_struct,
        tx_struct = tx_struct,
        hash_import = hash_import,
        hash_impl = generate_hash_impl(&spec.encoding)
    )
}

fn generate_hash_impl(encoding: &EncodingSpec) -> String {
    match encoding.hash.as_str() {
        "sha256" => r#"Sha256::digest(&self.raw_bytes).to_vec()"#.to_string(),
        "double-sha256" => r#"let hash1 = Sha256::digest(&self.raw_bytes);
        let hash2 = Sha256::digest(hash1);
        hash2.to_vec()"#
            .to_string(),
        "keccak256" => r#"Keccak256::digest(&self.raw_bytes).to_vec()"#.to_string(),
        _ => r#"unimplemented!("Hash algorithm not yet implemented")"#.to_string(),
    }
}

fn generate_property_tests(spec: &DecoderSpec) -> String {
    let decoder_struct = format!("{}Decoder", spec.chain.name);

    format!(
        r#"//! Property-based tests for {chain_name} decoder
//!
//! GENERATED from specification.

use decoder_{chain_lower}::*;
use proptest::prelude::*;
use decoder_test_utils::proptest_helpers::*;

proptest! {{
    #![proptest_config(ProptestConfig::with_cases(1000))]

    /// Property: Decoder never panics on arbitrary input
    #[test]
    fn prop_never_panics(bytes in arb_small_bytes()) {{
        prop_decoder_never_panics::<{decoder_struct}>(&bytes);
    }}

    /// Property: Validate format never panics
    #[test]
    fn prop_validate_never_panics(bytes in arb_small_bytes()) {{
        let _ = {decoder_struct}::validate_format(&bytes);
    }}
}}
"#,
        chain_name = spec.chain.name,
        chain_lower = spec.chain.name.to_lowercase(),
        decoder_struct = decoder_struct
    )
}

fn generate_readme(spec: &DecoderSpec) -> String {
    format!(
        r#"# {chain_name} Decoder

**GENERATED CODE** - Do not edit manually.

{description}

## Generation

This decoder was generated from `specs/{chain_lower}.toml`.

To regenerate:
```bash
cargo run -p decoder-generator -- generate specs/{chain_lower}.toml
```

## Encoding Details

- **Chain Family**: {family}
- **Endianness**: {endianness}
- **Hash Algorithm**: {hash}
- **Variable Encoding**: {var_encoding}

## Status

⚠️ **Work in Progress**: Field parsing implementation pending.

The decoder skeleton has been generated but field-level parsing logic
needs to be completed. See `src/lib.rs` and `src/parsing.rs`.

## Testing

```bash
# Run all tests
cargo test -p decoder-{chain_lower}

# Run property tests
cargo test -p decoder-{chain_lower} prop_

# Run with output
cargo test -p decoder-{chain_lower} -- --nocapture
```

## References

- Specification: `specs/{chain_lower}.toml`
- Generator: `crates/decoder-generator/`
"#,
        chain_name = spec.chain.name,
        chain_lower = spec.chain.name.to_lowercase(),
        description = spec
            .chain
            .description
            .as_ref()
            .unwrap_or(&"No description provided".to_string()),
        family = spec.chain.family,
        endianness = spec.encoding.endianness,
        hash = spec.encoding.hash,
        var_encoding = spec
            .encoding
            .var_encoding
            .as_ref()
            .unwrap_or(&"none".to_string())
    )
}
