use anyhow::{Context, Result};
use log::info;
use std::collections::HashMap;
use std::fs;
use std::path::Path;

use crate::analyzer::CodebaseAnalysis;
use crate::claude_api;

/// Generate all architecture diagrams using Anthropic API
pub fn generate_diagrams_anthropic(
    api_key: &str,
    model: &str,
    max_tokens: u32,
    temperature: f32,
    analysis: &CodebaseAnalysis,
) -> Result<HashMap<String, String>> {
    let mut diagrams = HashMap::new();

    // Generate different types of architecture diagrams
    let diagram_types = vec![
        ("architecture-overview.md", "overview"),
        ("dependency-graph.md", "dependency"),
        ("data-flow.md", "data-flow"),
        ("layered-architecture.md", "layer"),
    ];

    for (filename, diagram_type) in diagram_types {
        info!("Generating {} diagram...", diagram_type);

        match claude_api::generate_architecture_diagram(
            api_key,
            model,
            max_tokens,
            temperature,
            analysis,
            diagram_type,
        ) {
            Ok(diagram) => {
                let markdown = format_diagram_as_markdown(filename, diagram_type, &diagram);
                diagrams.insert(filename.to_string(), markdown);
            }
            Err(e) => {
                log::warn!("Failed to generate {} diagram: {}", diagram_type, e);
            }
        }
    }

    Ok(diagrams)
}

/// Generate all architecture diagrams using AWS Bedrock
pub fn generate_diagrams_bedrock(
    region: &str,
    model: &str,
    max_tokens: u32,
    temperature: f32,
    analysis: &CodebaseAnalysis,
) -> Result<HashMap<String, String>> {
    let mut diagrams = HashMap::new();

    // Generate different types of architecture diagrams
    let diagram_types = vec![
        ("architecture-overview.md", "overview"),
        ("dependency-graph.md", "dependency"),
        ("data-flow.md", "data-flow"),
        ("layered-architecture.md", "layer"),
    ];

    for (filename, diagram_type) in diagram_types {
        info!("Generating {} diagram...", diagram_type);

        match crate::bedrock_api::generate_architecture_diagram(
            region,
            model,
            max_tokens,
            temperature,
            analysis,
            diagram_type,
        ) {
            Ok(diagram) => {
                let markdown = format_diagram_as_markdown(filename, diagram_type, &diagram);
                diagrams.insert(filename.to_string(), markdown);
            }
            Err(e) => {
                log::warn!("Failed to generate {} diagram: {}", diagram_type, e);
            }
        }
    }

    Ok(diagrams)
}

/// Format a Mermaid diagram as a complete Markdown document
fn format_diagram_as_markdown(_filename: &str, diagram_type: &str, diagram: &str) -> String {
    let title = diagram_type
        .split('-')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().chain(chars).collect::<String>(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ");

    format!(
        r#"# {title}

> **Auto-generated**: This diagram is automatically generated by the `auto-update-docs` tool.
> Last updated: {date}

## Diagram

```mermaid
{diagram}
```

## Description

This diagram shows the {description} of the Universal Blockchain Decoder project.

### Key Components

{key_components}

## Maintenance

This diagram is automatically updated nightly by CI. To manually regenerate:

```bash
cargo run -p auto-update-docs -- --generate-diagrams
```

For more information, see the [Architecture Documentation](../CLAUDE.md).
"#,
        title = title,
        date = chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC"),
        diagram = diagram,
        description = get_diagram_description(diagram_type),
        key_components = generate_key_components(diagram),
    )
}

/// Get description for diagram type
fn get_diagram_description(diagram_type: &str) -> &str {
    match diagram_type {
        "overview" => "high-level architecture and module relationships",
        "dependency" => "dependency graph between modules and external crates",
        "data-flow" => "data flow from raw transaction bytes to canonical TxIR",
        "layer" => "layered architecture showing separation of concerns",
        _ => "architecture",
    }
}

/// Generate key components section from diagram
fn generate_key_components(diagram: &str) -> String {
    // Extract node names from Mermaid diagram (simplified)
    let mut components = Vec::new();

    for line in diagram.lines() {
        let line = line.trim();

        // Match various Mermaid node patterns
        if line.contains("[") && line.contains("]") {
            if let Some(start) = line.find('[') {
                if let Some(end) = line.find(']') {
                    let component = &line[start + 1..end];
                    if !component.is_empty() && !components.contains(&component.to_string()) {
                        components.push(component.to_string());
                    }
                }
            }
        }
    }

    if components.is_empty() {
        return "- See diagram above for component details\n".to_string();
    }

    components
        .into_iter()
        .take(10) // Limit to first 10 components
        .map(|c| format!("- **{}**\n", c))
        .collect::<Vec<_>>()
        .join("")
}

/// Write a diagram to file
pub fn write_diagram(docs_dir: &Path, filename: &str, content: &str) -> Result<()> {
    let diagrams_dir = docs_dir.join("diagrams");
    fs::create_dir_all(&diagrams_dir).context("Failed to create diagrams directory")?;

    let file_path = diagrams_dir.join(filename);
    fs::write(&file_path, content)
        .with_context(|| format!("Failed to write diagram to {:?}", file_path))?;

    Ok(())
}

/// Generate a module dependency graph (non-AI fallback)
#[allow(dead_code)]
pub fn generate_dependency_graph_fallback(analysis: &CodebaseAnalysis) -> String {
    let mut mermaid = String::from("graph TD\n");

    // Add nodes
    for module in &analysis.modules {
        let label = format!("{}[{}]", module.name.replace('-', "_"), module.name);
        mermaid.push_str(&format!("    {}\n", label));
    }

    mermaid.push('\n');

    // Add edges
    for module in &analysis.modules {
        if let Some(deps) = analysis.dependencies.get(&module.name) {
            for dep in deps {
                // Only show internal dependencies
                if analysis.modules.iter().any(|m| m.name == *dep) {
                    let from = module.name.replace('-', "_");
                    let to = dep.replace('-', "_");
                    mermaid.push_str(&format!("    {} --> {}\n", from, to));
                }
            }
        }
    }

    mermaid
}

/// Generate a simple overview diagram (non-AI fallback)
#[allow(dead_code)]
pub fn generate_overview_diagram_fallback(analysis: &CodebaseAnalysis) -> String {
    let mut mermaid = String::from("graph TB\n");

    // Core layer
    mermaid.push_str("    subgraph Core[\"Core Library\"]\n");
    for module in &analysis.modules {
        if matches!(module.module_type, crate::analyzer::ModuleType::Core) {
            mermaid.push_str(&format!(
                "        {}[\"{}\"]\n",
                module.name.replace('-', "_"),
                module.name
            ));
        }
    }
    mermaid.push_str("    end\n\n");

    // Decoders layer
    mermaid.push_str("    subgraph Decoders[\"Blockchain Decoders\"]\n");
    for module in &analysis.modules {
        if matches!(module.module_type, crate::analyzer::ModuleType::Decoder) {
            mermaid.push_str(&format!(
                "        {}[\"{}\"]\n",
                module.name.replace('-', "_"),
                module.name
            ));
        }
    }
    mermaid.push_str("    end\n\n");

    // Tools layer
    mermaid.push_str("    subgraph Tools[\"Development Tools\"]\n");
    for module in &analysis.modules {
        if matches!(module.module_type, crate::analyzer::ModuleType::Tool) {
            mermaid.push_str(&format!(
                "        {}[\"{}\"]\n",
                module.name.replace('-', "_"),
                module.name
            ));
        }
    }
    mermaid.push_str("    end\n\n");

    // Relationships
    mermaid.push_str("    Decoders --> Core\n");
    mermaid.push_str("    Tools --> Core\n");
    mermaid.push_str("    Tools --> Decoders\n");

    mermaid
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_diagram_as_markdown() {
        let diagram = "graph TD\n    A --> B";
        let markdown = format_diagram_as_markdown("test-diagram.md", "overview", diagram);

        assert!(markdown.contains("# Overview"));
        assert!(markdown.contains("```mermaid"));
        assert!(markdown.contains("graph TD"));
        assert!(markdown.contains("auto-update-docs"));
    }

    #[test]
    fn test_generate_key_components() {
        let diagram = r#"graph TD
    A[Core Library]
    B[Decoder]
    A --> B"#;

        let components = generate_key_components(diagram);
        assert!(components.contains("Core Library"));
        assert!(components.contains("Decoder"));
    }
}
