use anyhow::Result;
use clap::{ArgAction, Parser};
use log::{debug, info};
use std::path::PathBuf;

mod analyzer;
mod claude_api;
mod diagram_generator;
mod doc_updater;
mod git_utils;

#[derive(Parser, Debug)]
#[command(name = "auto-update-docs")]
#[command(about = "Automatically update documentation and architecture diagrams using Claude AI", long_about = None)]
struct Args {
    /// Repository root directory
    #[arg(long, default_value = ".")]
    repo_root: PathBuf,

    /// Anthropic API key (or set ANTHROPIC_API_KEY env var)
    #[arg(long, env)]
    api_key: String,

    /// Output directory for updated documentation
    #[arg(long, default_value = "docs")]
    docs_dir: PathBuf,

    /// Generate architecture diagrams
    #[arg(long, action = ArgAction::Set, default_value_t = true)]
    generate_diagrams: bool,

    /// Update existing documentation
    #[arg(long, action = ArgAction::Set, default_value_t = true)]
    update_docs: bool,

    /// Only analyze changes since this git ref (branch, tag, or commit)
    #[arg(long)]
    since: Option<String>,

    /// Create a git commit with the changes
    #[arg(long)]
    commit: bool,

    /// Push changes to remote
    #[arg(long)]
    push: bool,

    /// Create a pull request with changes
    #[arg(long)]
    create_pr: bool,

    /// Claude model to use
    #[arg(long, default_value = "claude-sonnet-4-5-20250929")]
    model: String,

    /// Maximum tokens for Claude response
    #[arg(long, default_value = "8000")]
    max_tokens: u32,

    /// Temperature for Claude API
    #[arg(long, default_value = "0.3")]
    temperature: f32,

    /// Verbose output
    #[arg(short, long)]
    verbose: bool,

    /// Dry run (don't write files)
    #[arg(long)]
    dry_run: bool,
}

fn main() -> Result<()> {
    let args = Args::parse();

    // Initialize logger
    if args.verbose {
        env_logger::Builder::from_default_env()
            .filter_level(log::LevelFilter::Debug)
            .init();
    } else {
        env_logger::Builder::from_default_env()
            .filter_level(log::LevelFilter::Info)
            .init();
    }

    info!("🚀 Starting documentation auto-update tool");
    info!("Repository: {:?}", args.repo_root);

    // Step 1: Analyze the codebase
    info!("📊 Analyzing codebase structure...");
    let analysis = analyzer::analyze_codebase(&args.repo_root, args.since.as_deref())?;

    debug!(
        "Analysis complete: {} modules, {} recent changes",
        analysis.module_count,
        analysis.changes.len()
    );

    // Step 2: Determine what documentation needs updating
    info!("🔍 Determining documentation updates needed...");
    let updates_needed = doc_updater::determine_updates(&args.repo_root, &analysis)?;

    if updates_needed.is_empty() {
        info!("✅ All documentation is up to date!");
        return Ok(());
    }

    info!(
        "📝 Found {} documentation items to update",
        updates_needed.len()
    );

    // Step 3: Generate architecture diagrams using Claude
    if args.generate_diagrams {
        info!("🎨 Generating architecture diagrams...");
        let diagrams = diagram_generator::generate_diagrams(
            &args.api_key,
            &args.model,
            args.max_tokens,
            args.temperature,
            &analysis,
        )?;

        if !args.dry_run {
            for (name, diagram) in diagrams {
                diagram_generator::write_diagram(&args.docs_dir, &name, &diagram)?;
                info!("  ✓ Generated {}", name);
            }
        } else {
            info!(
                "  (Dry run: {} diagrams would be generated)",
                diagrams.len()
            );
        }
    }

    // Step 4: Update documentation using Claude
    if args.update_docs {
        info!("📚 Updating documentation...");
        for update in &updates_needed {
            info!("  Updating {}...", update.doc_path.display());

            let updated_content = claude_api::generate_doc_update(
                &args.api_key,
                &args.model,
                args.max_tokens,
                args.temperature,
                update,
                &analysis,
            )?;

            if !args.dry_run {
                doc_updater::write_doc(&update.doc_path, &updated_content)?;
                info!("  ✓ Updated {}", update.doc_path.display());
            }
        }
    }

    // Step 5: Git operations
    if !args.dry_run {
        if args.commit {
            info!("📦 Creating git commit...");
            let commit_msg = format!(
                "docs: Auto-update documentation and diagrams\n\n\
                 Updated {} documentation files\n\
                 Generated {} architecture diagrams\n\n\
                 Generated by auto-update-docs tool",
                updates_needed.len(),
                if args.generate_diagrams {
                    "multiple"
                } else {
                    "no"
                }
            );
            git_utils::commit_changes(&args.repo_root, &commit_msg)?;
            info!("  ✓ Committed changes");

            if args.push {
                info!("⬆️  Pushing to remote...");
                git_utils::push_changes(&args.repo_root)?;
                info!("  ✓ Pushed changes");
            }

            if args.create_pr {
                info!("🔀 Creating pull request...");
                git_utils::create_pull_request(&args.repo_root, &commit_msg)?;
                info!("  ✓ Created pull request");
            }
        }
    } else {
        info!("(Dry run: no changes written)");
    }

    info!("✨ Documentation update complete!");

    Ok(())
}
