//! Cosmos chain registry
//!
//! This module provides compile-time embedded chain information for all Cosmos chains.
//! The data is loaded from a Borsh-serialized binary file generated by the
//! registry-generator tool.

use borsh::BorshDeserialize;
use std::collections::HashMap;

/// Cosmos chain information (minimal subset for decoder use)
#[derive(Debug, Clone, BorshDeserialize)]
pub struct CosmosChainInfo {
    pub chain_name: String,
    pub chain_id: String,
    pub pretty_name: String,
    pub bech32_prefix: String,
    pub slip44: u32,
    pub network_type: String, // "mainnet" | "testnet"
}

/// Cosmos chain registry
///
/// Provides access to metadata for all Cosmos chains. The data is embedded
/// at compile time from a Borsh-serialized binary file.
pub struct CosmosRegistry {
    chains: HashMap<String, CosmosChainInfo>,
}

impl CosmosRegistry {
    /// Create a new registry by deserializing the embedded Borsh data
    ///
    /// # Panics
    ///
    /// Panics if the embedded data is corrupted or cannot be deserialized.
    /// This should never happen in practice as the data is validated at build time.
    pub fn new() -> Self {
        // Embed Borsh binary at compile time (zero runtime I/O)
        const CHAINS_BORSH: &[u8] = include_bytes!("../data/cosmos-chains.borsh");

        let chains: HashMap<String, CosmosChainInfo> =
            BorshDeserialize::try_from_slice(CHAINS_BORSH)
                .expect("Failed to deserialize Cosmos chains");

        Self { chains }
    }

    /// Get chain information by chain ID (e.g., "cosmoshub-4")
    pub fn get_chain(&self, chain_id: &str) -> Option<&CosmosChainInfo> {
        self.chains.get(chain_id)
    }

    /// Get chain information by chain name (e.g., "cosmoshub")
    pub fn get_chain_by_name(&self, chain_name: &str) -> Option<&CosmosChainInfo> {
        self.chains.values().find(|c| c.chain_name == chain_name)
    }

    /// Get all chains
    pub fn all_chains(&self) -> impl Iterator<Item = &CosmosChainInfo> {
        self.chains.values()
    }

    /// Get number of chains in registry
    pub fn chain_count(&self) -> usize {
        self.chains.len()
    }

    /// Check if a chain ID exists
    pub fn has_chain(&self, chain_id: &str) -> bool {
        self.chains.contains_key(chain_id)
    }
}

impl Default for CosmosRegistry {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_registry_loads() {
        let registry = CosmosRegistry::new();
        assert!(registry.chain_count() > 0, "Registry should contain chains");
    }

    #[test]
    fn test_get_cosmoshub() {
        let registry = CosmosRegistry::new();

        // Try to find Cosmos Hub by chain ID
        let cosmoshub = registry.all_chains().find(|c| c.chain_name == "cosmoshub");

        if let Some(chain) = cosmoshub {
            assert_eq!(chain.bech32_prefix, "cosmos");
            assert_eq!(chain.slip44, 118);
        }
    }

    #[test]
    fn test_registry_iteration() {
        let registry = CosmosRegistry::new();
        let count = registry.all_chains().count();
        assert_eq!(count, registry.chain_count());
    }
}
