//! Superchain (OP Stack) registry
//!
//! This module provides compile-time embedded chain information for all OP Stack chains.
//! The data is loaded from a Borsh-serialized binary file generated by the
//! registry-generator tool.

use borsh::BorshDeserialize;

/// OP Stack chain information (minimal subset for decoder use)
#[derive(Debug, Clone, BorshDeserialize)]
pub struct SuperchainInfo {
    pub name: String,
    pub chain_id: u64,
    pub rpc: Vec<String>,
    pub explorers: Vec<String>,
    pub superchain_level: u8,
    pub data_availability_type: String, // "eth-da" | "alt-da"
}

/// Superchain (OP Stack) registry
///
/// Provides access to metadata for all OP Stack chains. The data is embedded
/// at compile time from a Borsh-serialized binary file.
pub struct SuperchainRegistry {
    chains: Vec<SuperchainInfo>,
}

impl SuperchainRegistry {
    /// Create a new registry by deserializing the embedded Borsh data
    ///
    /// # Panics
    ///
    /// Panics if the embedded data is corrupted or cannot be deserialized.
    /// This should never happen in practice as the data is validated at build time.
    pub fn new() -> Self {
        // Embed Borsh binary at compile time (zero runtime I/O)
        const CHAINS_BORSH: &[u8] = include_bytes!("../data/op-chains.borsh");

        let chains: Vec<SuperchainInfo> = BorshDeserialize::try_from_slice(CHAINS_BORSH)
            .expect("Failed to deserialize OP Stack chains");

        Self { chains }
    }

    /// Get chain information by chain ID
    pub fn get_chain(&self, chain_id: u64) -> Option<&SuperchainInfo> {
        self.chains.iter().find(|c| c.chain_id == chain_id)
    }

    /// Get chain information by name
    pub fn get_chain_by_name(&self, name: &str) -> Option<&SuperchainInfo> {
        self.chains.iter().find(|c| c.name == name)
    }

    /// Get all chains
    pub fn all_chains(&self) -> impl Iterator<Item = &SuperchainInfo> {
        self.chains.iter()
    }

    /// Get number of chains in registry
    pub fn chain_count(&self) -> usize {
        self.chains.len()
    }

    /// Check if a chain ID exists
    pub fn has_chain(&self, chain_id: u64) -> bool {
        self.chains.iter().any(|c| c.chain_id == chain_id)
    }
}

impl Default for SuperchainRegistry {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_registry_loads() {
        let registry = SuperchainRegistry::new();
        assert!(registry.chain_count() > 0, "Registry should contain chains");
    }

    #[test]
    fn test_get_optimism() {
        let registry = SuperchainRegistry::new();

        // Optimism mainnet has chain ID 10
        let optimism = registry.get_chain(10);
        assert!(
            optimism.is_some(),
            "Should find Optimism mainnet (chain ID 10)"
        );

        if let Some(chain) = optimism {
            assert!(
                chain.name.to_lowercase().contains("optimism")
                    || chain.name.to_lowercase().contains("op ")
            );
        }
    }

    #[test]
    fn test_get_base() {
        let registry = SuperchainRegistry::new();

        // Base mainnet has chain ID 8453
        let base = registry.get_chain(8453);
        if let Some(chain) = base {
            assert!(chain.name.to_lowercase().contains("base"));
        }
    }

    #[test]
    fn test_registry_iteration() {
        let registry = SuperchainRegistry::new();
        let count = registry.all_chains().count();
        assert_eq!(count, registry.chain_count());
        assert!(count > 10, "Should have multiple OP Stack chains");
    }
}
