//! Optimism Transaction Types
//!
//! Optimism supports standard Ethereum transactions plus a special deposit transaction type
//! (0x7E) for L1→L2 communication.

use borsh::{BorshDeserialize, BorshSerialize};
use decoder_ethereum::types::EthereumTransaction;
use serde::{Deserialize, Serialize};
use universal_decoder_core::prelude::*;

/// Optimism transaction type (either standard EVM or deposit)
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, BorshSerialize, BorshDeserialize)]
pub enum OptimismTransaction {
    /// Standard Ethereum-compatible transaction (types 0x00, 0x01, 0x02)
    Standard(EthereumTransaction),

    /// Optimism-specific deposit transaction (type 0x7E)
    ///
    /// Deposit transactions are generated by the L1→L2 messaging system
    /// and do not require signatures. They are derived from L1 deposit events.
    Deposit(DepositTransaction),
}

/// Optimism Deposit Transaction (Type 0x7E)
///
/// Deposit transactions are used for L1→L2 communication in Optimism.
/// They are derived from `TransactionDeposited` events emitted by the OptimismPortal
/// contract on L1.
///
/// ## Key Properties
///
/// - **No Signature**: Authorization is handled by chain derivation, not cryptographic signatures
/// - **Source Hash**: Uniquely identifies the L1 origin of this deposit
/// - **Mint**: Amount of ETH minted on L2 (increases total L2 ETH supply)
/// - **Value**: Amount of ETH transferred to the recipient
///
/// ## Transaction Types
///
/// 1. **L1 Attributes Deposit**: First transaction in every L2 block, sets L1 block metadata
/// 2. **User Deposit**: User-initiated deposit from L1 via OptimismPortal contract
///
/// ## Specification
///
/// See: https://specs.optimism.io/protocol/deposits.html
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, BorshSerialize, BorshDeserialize)]
pub struct DepositTransaction {
    /// Source hash that uniquely identifies the origin of this deposit on L1
    ///
    /// Computed from:
    /// - L1 block hash
    /// - L1 log index (for user deposits)
    /// - Deposit count (for L1 attributes deposits)
    pub source_hash: [u8; 32],

    /// Address that sent the deposit (derived from L1 deposit event)
    pub from: [u8; 20],

    /// Recipient address (or None for contract creation)
    pub to: Option<[u8; 20]>,

    /// Amount of ETH to mint on L2
    ///
    /// This increases the total L2 ETH supply. Used to match L1 deposits.
    pub mint: u128,

    /// Amount of ETH to transfer to the recipient
    ///
    /// This must be ≤ mint. The difference (mint - value) stays with the sender.
    pub value: u128,

    /// Gas limit for the transaction
    pub gas_limit: u64,

    /// Whether this is a contract creation transaction
    pub is_creation: bool,

    /// Transaction calldata
    pub data: Vec<u8>,

    /// Raw transaction bytes (for re-encoding)
    pub raw_bytes: Vec<u8>,
}

impl DepositTransaction {
    /// Transaction type identifier for deposit transactions
    pub const TYPE_ID: u8 = 0x7E;

    /// Creates a new deposit transaction
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        source_hash: [u8; 32],
        from: [u8; 20],
        to: Option<[u8; 20]>,
        mint: u128,
        value: u128,
        gas_limit: u64,
        is_creation: bool,
        data: Vec<u8>,
        raw_bytes: Vec<u8>,
    ) -> Self {
        Self {
            source_hash,
            from,
            to,
            mint,
            value,
            gas_limit,
            is_creation,
            data,
            raw_bytes,
        }
    }

    /// Returns true if this is an L1 attributes deposit (first tx in block)
    ///
    /// L1 attributes deposits have:
    /// - to = 0x4200000000000000000000000000000000000015 (L1Block predeploy)
    /// - Special calldata format
    pub fn is_l1_attributes_deposit(&self) -> bool {
        const L1_BLOCK_PREDEPLOY: [u8; 20] = [
            0x42, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x15,
        ];

        self.to == Some(L1_BLOCK_PREDEPLOY)
    }

    /// Returns true if this is a user-initiated deposit
    pub fn is_user_deposit(&self) -> bool {
        !self.is_l1_attributes_deposit()
    }

    /// Validate deposit transaction invariants
    ///
    /// ## Invariants
    ///
    /// 1. value ≤ mint (can't transfer more than minted)
    /// 2. If is_creation is true, to must be None
    /// 3. If is_creation is false, to must be Some
    pub fn validate(&self) -> Result<()> {
        // Invariant 1: value ≤ mint
        if self.value > self.mint {
            return Err(DecoderError::invalid_structure(format!(
                "Invalid deposit: value ({}) > mint ({})",
                self.value, self.mint
            )));
        }

        // Invariant 2 & 3: is_creation consistency
        match (self.is_creation, self.to) {
            (true, Some(_)) => {
                return Err(DecoderError::invalid_structure(
                    "Invalid deposit: is_creation=true but to address is present".to_string(),
                ))
            }
            (false, None) => {
                return Err(DecoderError::invalid_structure(
                    "Invalid deposit: is_creation=false but to address is missing".to_string(),
                ))
            }
            _ => {} // Valid combinations
        }

        Ok(())
    }
}

impl OptimismTransaction {
    /// Returns the transaction type identifier
    pub fn tx_type(&self) -> u8 {
        match self {
            OptimismTransaction::Standard(eth_tx) => eth_tx.tx_type_u8(),
            OptimismTransaction::Deposit(_) => DepositTransaction::TYPE_ID,
        }
    }

    /// Returns true if this is a deposit transaction
    pub fn is_deposit(&self) -> bool {
        matches!(self, OptimismTransaction::Deposit(_))
    }

    /// Returns true if this is a standard Ethereum transaction
    pub fn is_standard(&self) -> bool {
        matches!(self, OptimismTransaction::Standard(_))
    }

    /// Get the sender address
    pub fn from(&self) -> [u8; 20] {
        match self {
            OptimismTransaction::Standard(eth_tx) => eth_tx.get_from(),
            OptimismTransaction::Deposit(deposit) => deposit.from,
        }
    }

    /// Get the recipient address (if any)
    pub fn to(&self) -> Option<[u8; 20]> {
        match self {
            OptimismTransaction::Standard(eth_tx) => eth_tx.to,
            OptimismTransaction::Deposit(deposit) => deposit.to,
        }
    }

    /// Get the transaction value (amount transferred)
    pub fn value(&self) -> u128 {
        match self {
            OptimismTransaction::Standard(eth_tx) => eth_tx.value,
            OptimismTransaction::Deposit(deposit) => deposit.value,
        }
    }

    /// Get the transaction data/calldata
    pub fn data(&self) -> &[u8] {
        match self {
            OptimismTransaction::Standard(eth_tx) => &eth_tx.data,
            OptimismTransaction::Deposit(deposit) => &deposit.data,
        }
    }
}

impl ChainEncoder for OptimismTransaction {
    /// Re-encode the Optimism transaction back to its original byte format
    ///
    /// Since we store the original raw bytes during decoding, this simply
    /// returns a clone of those bytes, guaranteeing exact reconstruction.
    ///
    /// # Formal Properties
    ///
    /// This implementation trivially satisfies the injective property:
    /// ```text
    /// ∀ tx_bytes: OptimismDecoder::decode(tx_bytes)?.to_bytes()? == tx_bytes
    /// ```
    ///
    /// Because we store `raw_bytes` during decode, the roundtrip is guaranteed.
    fn to_bytes(&self) -> Result<Vec<u8>> {
        match self {
            OptimismTransaction::Standard(eth_tx) => eth_tx.to_bytes(),
            OptimismTransaction::Deposit(deposit) => Ok(deposit.raw_bytes.clone()),
        }
    }
}

impl<'a> Canonicalizer<'a> for OptimismTransaction {
    const VERSION: u8 = 1;

    fn canonicalize(&'a self) -> Result<TxIR<'a, 1>> {
        use crate::OptimismChain;

        match self {
            OptimismTransaction::Standard(eth_tx) => {
                // For standard transactions, delegate to Ethereum canonicalization
                // but update the chain to OptimismChain
                let tx_ir = eth_tx.canonicalize()?;

                // Note: We can't directly modify the chain in TxIR since it's a reference
                // For now, we'll return the Ethereum canonicalization
                // In a full implementation, we'd need to reconstruct with OptimismChain
                Ok(tx_ir)
            }
            OptimismTransaction::Deposit(deposit) => {
                // Build metadata
                let extra = format!(
                    r#"{{"tx_type":"deposit","source_hash":"{}","mint":{},"is_creation":{},"is_l1_attributes":{}}}"#,
                    universal_decoder_core::hex::encode(deposit.source_hash),
                    deposit.mint,
                    deposit.is_creation,
                    deposit.is_l1_attributes_deposit()
                );

                let metadata = TxMetadata {
                    tx_hash: {
                        // Compute hash of deposit transaction
                        use sha3::{Digest, Keccak256};
                        let mut bytes = vec![0x7E]; // Type prefix
                        bytes.extend_from_slice(&borsh::to_vec(deposit).unwrap());
                        Keccak256::digest(&bytes).to_vec()
                    },
                    block_height: None,
                    timestamp: None,
                    size: 0, // Would need raw bytes
                    extra,
                };

                // No signatures for deposit transactions (chain derivation auth)
                let authorization = AuthorizationPackage {
                    signatures: vec![],
                    public_keys: vec![],
                    signature_scheme: SignatureScheme::Custom(0), // 0 = No signature (chain derivation)
                };

                // Build operations
                let mut operations = Vec::new();

                // ETH minting operation (L1 -> L2 deposit)
                if deposit.mint > 0 {
                    operations.push(Operation::Transfer(Transfer {
                        from: Address {
                            bytes: vec![],
                            human_readable: Some("L1Bridge".to_string()),
                        },
                        to: Address {
                            bytes: deposit.from.to_vec(),
                            human_readable: Some(format!(
                                "0x{}",
                                universal_decoder_core::hex::encode(deposit.from)
                            )),
                        },
                        amount: Amount {
                            value: deposit.mint,
                            decimals: 18,
                        },
                        asset: AssetId::Native,
                    }));
                }

                // Value transfer operation (if different from mint)
                if deposit.value > 0 && deposit.value != deposit.mint {
                    operations.push(Operation::Transfer(Transfer {
                        from: Address {
                            bytes: deposit.from.to_vec(),
                            human_readable: Some(format!(
                                "0x{}",
                                universal_decoder_core::hex::encode(deposit.from)
                            )),
                        },
                        to: Address {
                            bytes: deposit.to.map(|a| a.to_vec()).unwrap_or_default(),
                            human_readable: deposit
                                .to
                                .map(|a| format!("0x{}", universal_decoder_core::hex::encode(a))),
                        },
                        amount: Amount {
                            value: deposit.value,
                            decimals: 18,
                        },
                        asset: AssetId::Native,
                    }));
                }

                // Contract deployment or call
                if deposit.is_creation {
                    operations.push(Operation::ContractDeploy(ContractDeploy {
                        bytecode: deposit.data.clone(),
                        constructor_args: vec![],
                        value: Amount {
                            value: deposit.value,
                            decimals: 18,
                        },
                    }));
                } else if !deposit.data.is_empty() {
                    let method = if deposit.data.len() >= 4 {
                        deposit.data[0..4].to_vec()
                    } else {
                        vec![]
                    };

                    operations.push(Operation::ContractCall(ContractCall {
                        contract: Address {
                            bytes: deposit.to.map(|a| a.to_vec()).unwrap_or_default(),
                            human_readable: deposit
                                .to
                                .map(|a| format!("0x{}", universal_decoder_core::hex::encode(a))),
                        },
                        method,
                        data: deposit.data.clone(),
                        value: Some(Amount {
                            value: deposit.value,
                            decimals: 18,
                        }),
                        resource_limits: ResourceLimits {
                            max_units: deposit.gas_limit,
                            unit_price: 0, // No gas price for deposit transactions
                            resource_type: ResourceType::Gas,
                        },
                    }));
                }

                // Build state deltas
                let mut account_changes = vec![];

                // Sender gets minted ETH
                if deposit.mint > 0 {
                    account_changes.push(AccountChange {
                        address: Address {
                            bytes: deposit.from.to_vec(),
                            human_readable: Some(format!(
                                "0x{}",
                                universal_decoder_core::hex::encode(deposit.from)
                            )),
                        },
                        nonce: None,
                        balance_change: deposit.mint as i128,
                        storage_changes: vec![],
                    });
                }

                // Recipient receives value (if different from sender)
                if deposit.value > 0 && deposit.to.is_some() {
                    account_changes.push(AccountChange {
                        address: Address {
                            bytes: deposit.to.unwrap().to_vec(),
                            human_readable: Some(format!(
                                "0x{}",
                                universal_decoder_core::hex::encode(deposit.to.unwrap())
                            )),
                        },
                        nonce: None,
                        balance_change: deposit.value as i128,
                        storage_changes: vec![],
                    });
                }

                let state_deltas = StateDeltas {
                    inputs: vec![],
                    outputs: vec![],
                    account_changes,
                };

                Ok(TxIR::new(
                    &OptimismChain,
                    metadata,
                    authorization,
                    operations,
                    state_deltas,
                ))
            }
        }
    }

    fn validate(&self) -> Result<()> {
        match self {
            OptimismTransaction::Standard(eth_tx) => eth_tx.validate(),
            OptimismTransaction::Deposit(deposit) => deposit.validate(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_deposit_transaction_creation() {
        let deposit = DepositTransaction::new(
            [1u8; 32],
            [2u8; 20],
            Some([3u8; 20]),
            1000,
            500,
            21000,
            false,
            vec![1, 2, 3],
            vec![],
        );

        assert_eq!(deposit.source_hash, [1u8; 32]);
        assert_eq!(deposit.from, [2u8; 20]);
        assert_eq!(deposit.to, Some([3u8; 20]));
        assert_eq!(deposit.mint, 1000);
        assert_eq!(deposit.value, 500);
        assert_eq!(deposit.gas_limit, 21000);
        assert!(!deposit.is_creation);
        assert_eq!(deposit.data, vec![1, 2, 3]);
    }

    #[test]
    fn test_deposit_type_id() {
        assert_eq!(DepositTransaction::TYPE_ID, 0x7E);
    }

    #[test]
    fn test_l1_attributes_deposit_detection() {
        let l1_block_predeploy = [
            0x42, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x15,
        ];

        let l1_attrs = DepositTransaction::new(
            [0u8; 32],
            [0u8; 20],
            Some(l1_block_predeploy),
            0,
            0,
            1_000_000,
            false,
            vec![],
            vec![],
        );

        assert!(l1_attrs.is_l1_attributes_deposit());
        assert!(!l1_attrs.is_user_deposit());
    }

    #[test]
    fn test_user_deposit_detection() {
        let user_deposit = DepositTransaction::new(
            [0u8; 32],
            [1u8; 20],
            Some([2u8; 20]),
            1000,
            1000,
            100_000,
            false,
            vec![],
            vec![],
        );

        assert!(!user_deposit.is_l1_attributes_deposit());
        assert!(user_deposit.is_user_deposit());
    }

    #[test]
    fn test_deposit_validation_valid() {
        let deposit = DepositTransaction::new(
            [0u8; 32],
            [1u8; 20],
            Some([2u8; 20]),
            1000,
            500, // value < mint
            100_000,
            false,
            vec![],
            vec![],
        );

        assert!(deposit.validate().is_ok());
    }

    #[test]
    fn test_deposit_validation_value_exceeds_mint() {
        let deposit = DepositTransaction::new(
            [0u8; 32],
            [1u8; 20],
            Some([2u8; 20]),
            500,
            1000, // value > mint: INVALID
            100_000,
            false,
            vec![],
            vec![],
        );

        assert!(deposit.validate().is_err());
        let err = deposit.validate().unwrap_err();
        let err_msg = format!("{:?}", err);
        assert!(err_msg.contains("value") || err_msg.contains("mint"));
    }

    #[test]
    fn test_deposit_validation_creation_with_to() {
        let deposit = DepositTransaction::new(
            [0u8; 32],
            [1u8; 20],
            Some([2u8; 20]), // to is set
            1000,
            1000,
            100_000,
            true, // but is_creation=true: INVALID
            vec![],
            vec![],
        );

        assert!(deposit.validate().is_err());
        let err = deposit.validate().unwrap_err();
        let err_msg = format!("{:?}", err);
        assert!(err_msg.contains("is_creation"));
    }

    #[test]
    fn test_deposit_validation_non_creation_without_to() {
        let deposit = DepositTransaction::new(
            [0u8; 32],
            [1u8; 20],
            None, // to is None
            1000,
            1000,
            100_000,
            false, // but is_creation=false: INVALID
            vec![],
            vec![],
        );

        assert!(deposit.validate().is_err());
        let err = deposit.validate().unwrap_err();
        let err_msg = format!("{:?}", err);
        assert!(err_msg.contains("is_creation"));
    }

    #[test]
    fn test_optimism_transaction_type_detection() {
        use decoder_ethereum::types::TxType;

        let eth_tx = EthereumTransaction {
            tx_type: TxType::Eip1559,
            chain_id: Some(10),
            nonce: 0,
            gas_limit: 21000,
            max_fee_per_gas: Some(1000),
            max_priority_fee_per_gas: Some(100),
            gas_price: None,
            to: Some([1u8; 20]),
            value: 1000,
            data: vec![],
            access_list: vec![],
            v: 0,
            r: [0u8; 32],
            s: [0u8; 32],
            raw_bytes: vec![],
        };

        let standard_tx = OptimismTransaction::Standard(eth_tx);
        assert!(standard_tx.is_standard());
        assert!(!standard_tx.is_deposit());
        assert_eq!(standard_tx.tx_type(), 0x02);

        let deposit_tx = OptimismTransaction::Deposit(DepositTransaction::new(
            [0u8; 32],
            [1u8; 20],
            Some([2u8; 20]),
            1000,
            1000,
            100_000,
            false,
            vec![],
            vec![],
        ));

        assert!(deposit_tx.is_deposit());
        assert!(!deposit_tx.is_standard());
        assert_eq!(deposit_tx.tx_type(), 0x7E);
    }

    #[test]
    fn test_optimism_transaction_accessors() {
        let deposit = DepositTransaction::new(
            [0u8; 32],
            [1u8; 20],
            Some([2u8; 20]),
            1000,
            500,
            100_000,
            false,
            vec![0xaa, 0xbb],
            vec![],
        );

        let tx = OptimismTransaction::Deposit(deposit);

        assert_eq!(tx.from(), [1u8; 20]);
        assert_eq!(tx.to(), Some([2u8; 20]));
        assert_eq!(tx.value(), 500);
        assert_eq!(tx.data(), &[0xaa, 0xbb]);
    }

    #[test]
    fn test_deposit_transaction_borsh_serialization() {
        let deposit = DepositTransaction::new(
            [1u8; 32],
            [2u8; 20],
            Some([3u8; 20]),
            1000,
            500,
            21000,
            false,
            vec![1, 2, 3],
            Vec::new(),
        );

        let serialized = borsh::to_vec(&deposit).expect("Failed to serialize");
        let deserialized: DepositTransaction =
            borsh::from_slice(&serialized).expect("Failed to deserialize");

        assert_eq!(deposit, deserialized);
    }
}
