//! Task executor using Claude Code

use anyhow::{Context, Result};
use chrono::Utc;
use log::{info, warn};
use std::env;

use crate::git::GitHelper;
use crate::task::Task;

pub struct TaskExecutor {
    anthropic_api_key: Option<String>,
}

impl TaskExecutor {
    pub fn new() -> Result<Self> {
        let anthropic_api_key = env::var("ANTHROPIC_API_KEY").ok();

        if anthropic_api_key.is_none() {
            warn!("ANTHROPIC_API_KEY not set - Claude Code invocation will be placeholder");
        }

        Ok(Self { anthropic_api_key })
    }

    /// Execute a task
    pub async fn execute(&self, task: &Task, dry_run: bool) -> Result<String> {
        println!("\n{}", "=".repeat(80));
        println!("Executing Task: {}", task.title);
        println!("Phase: {}", task.phase);
        println!("Priority: {}", task.priority);
        println!("ROI Score: {:.2}", task.roi_score);
        println!(
            "Time Estimate: {}",
            task.time_estimate.as_ref().unwrap_or(&"N/A".to_string())
        );
        println!("{}", "=".repeat(80));
        println!();

        if dry_run {
            info!("[DRY RUN] Would execute task, but skipping...");
            return Ok("Dry run - no actual execution".to_string());
        }

        // Create branch name
        let timestamp = Utc::now().format("%Y%m%d-%H%M%S");
        let branch_name = format!("claude/automate-{}-{}", task.id, timestamp);

        // 1. Create and checkout branch
        info!("Creating branch: {}", branch_name);
        GitHelper::create_branch(&branch_name)?;

        // 2. Build prompt and invoke Claude Code
        let prompt = self.build_prompt(task);
        info!("Invoking Claude Code...");
        self.invoke_claude_code(&prompt).await?;

        // 3. Run quality checks
        info!("Running quality checks...");
        self.run_quality_checks()?;

        // 4. Run tests
        info!("Running tests...");
        self.run_tests()?;

        // 5. Commit changes
        let commit_msg = format!(
            "automate: {}\n\n{}\n\nGenerated by autonomous executor",
            task.title,
            &task.description[..task.description.len().min(200)]
        );
        info!("Committing changes...");
        GitHelper::add_all()?;
        GitHelper::commit(&commit_msg)?;

        // 6. Push branch
        info!("Pushing to remote...");
        GitHelper::push(&branch_name)?;

        Ok(format!(
            "Successfully completed task on branch {}",
            branch_name
        ))
    }

    /// Build prompt for Claude Code
    fn build_prompt(&self, task: &Task) -> String {
        let completed_items = task
            .completed_items
            .iter()
            .map(|s| format!("- ✅ {}", s))
            .collect::<Vec<_>>()
            .join("\n");

        let remaining_items = task
            .remaining_items
            .iter()
            .map(|s| format!("- [ ] {}", s))
            .collect::<Vec<_>>()
            .join("\n");

        format!(
            r#"# Autonomous Task Execution

You are working autonomously to complete a task from the Universal Blockchain Decoder roadmap.

## Task Details

**Phase**: {}
**Title**: {}
**Priority**: {}
**Time Estimate**: {}
**Status**: {}

## Description

{}

## Completed Items

{}

## Remaining Items

{}

## Instructions

1. Implement the remaining items listed above
2. Follow the design principles in CLAUDE.md
3. Run `cargo fmt --all && cargo clippy --all --all-targets --all-features -- -D warnings` before committing
4. Write comprehensive tests (unit + property + integration)
5. Update documentation if needed
6. Mark todos as completed in TodoWrite as you finish each item

## Success Criteria

- ✅ All remaining items completed
- ✅ All tests pass (`cargo test --all`)
- ✅ No clippy warnings
- ✅ Code formatted (`cargo fmt --all`)
- ✅ Documentation updated (if needed)

## Important

- Follow the pre-commit checks in CLAUDE.md
- Use TodoWrite to track your progress
- Commit with clear, descriptive messages
- Push to a branch starting with 'claude/'

Begin implementation now. Work autonomously until all success criteria are met.
"#,
            task.phase,
            task.title,
            task.priority,
            task.time_estimate.as_ref().unwrap_or(&"N/A".to_string()),
            task.status,
            task.description,
            completed_items,
            remaining_items
        )
    }

    /// Invoke Claude Code with the given prompt
    ///
    /// TODO: Implement actual Anthropic API call when SDK is available
    async fn invoke_claude_code(&self, prompt: &str) -> Result<()> {
        if self.anthropic_api_key.is_none() {
            info!("[PLACEHOLDER] Claude Code invocation would happen here");
            info!("Prompt preview:\n{}", &prompt[..prompt.len().min(200)]);
            info!("...\n");

            // For now, just return success
            // In production, this would:
            // 1. Call Anthropic API with the prompt
            // 2. Stream the response
            // 3. Execute tool calls (file edits, commands, etc.)
            // 4. Return when task is complete

            warn!("Claude Code invocation is a placeholder - no actual changes made");
            return Ok(());
        }

        // TODO: Implement actual API call
        // Example structure:
        // let client = AnthropicClient::new(self.anthropic_api_key.as_ref().unwrap());
        // let response = client.messages().create(prompt).await?;
        // ... process response and tool calls ...

        Ok(())
    }

    /// Run quality checks (fmt, clippy)
    fn run_quality_checks(&self) -> Result<()> {
        info!("Running cargo fmt...");
        GitHelper::cargo_fmt().context("Cargo fmt failed")?;

        info!("Running cargo clippy...");
        GitHelper::cargo_clippy().context("Cargo clippy failed")?;

        Ok(())
    }

    /// Run test suite
    fn run_tests(&self) -> Result<()> {
        info!("Running cargo test...");
        GitHelper::cargo_test().context("Cargo test failed")?;

        Ok(())
    }
}
